variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch

image: mlanguage/mlang:0.2

before_script:
  - eval $(opam env)


stages:
  - build
  - tests
  - optimization-tests

build_job:
  stage: build
  script:
    - make build
  artifacts:
    paths:
    - _build/default/src/main.exe
    expire_in: 2h

test_interpreter:
  stage: tests
  script:
    - OPTIMIZE=0 make tests

test_c_backend:
  stage: tests
  script:
    - make test_c_backend
  allow_failure: true

test_py_backend:
  stage: tests
  script:
    - make test_python_backend

test_optims:
  stage: optimization-tests
  script:
    - OPTIMIZE=1 make tests
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - when: never
