image: "ocaml:4.07"

before_script:
  - sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
  - opam switch create 4.07.1
  - opam install ppx_deriving ANSITerminal re ocamlgraph z3 dune menhir cmdliner dune-build-info visitors parmap -y

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch

image: mopsa-build

stages:
- build
- test

build_job:
  stage: build
  script:
    - eval `opam config env`
    - make build
  artifacts:
    paths:
    - ./main.exe
    - ./_build/default/src/main.exe
    expire_in: 2h

tests:
  stage: test
  dependencies: [build_job]
  script:
    - eval `opam config env`
    - make tests
