variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch

image: ocaml/opam:ubuntu-20.04-ocaml-4.11

before_script:
  - sudo apt install -y -qq libgmp-dev libmpfr-dev m4 perl python3
  - OPAMYES=TRUE make deps

stages:
  - build
  - tests
  - optimization-tests

build_job:
  stage: build
  script:
    - make build
  artifacts:
    paths:
    - _build/default/src/main.exe
    expire_in: 2h

test_interpreter:
  stage: tests
  script:
    - make tests

test_c_backend:
  stage: tests
  script:
    - make test_c_backend

test_py_backend:
  stage: tests
  script:
    - make test_python_backend

test_optims:
  stage: optimization-tests
  script:
    - OPTIMIZE=1 make tests
